name: 📅 Daily TPM Log Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' # runs at 1 PM UTC (adjust as needed)

jobs:
  log-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Log timestamped commit
        run: |
          echo "✅ TPM Daily Log Entry: $(date)" >> log/$(date +'%Y-%m-%d').md
